# See https://pre-commit.com/ for usage and config
# pre-commit install
# need commit-msg hook for commitzen
# pre-commit install --hook-type commit-msg

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
    -   id: check-vcs-permalinks
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
    -   id: mixed-line-ending
        args: ['--fix=lf']
    -   id: check-toml
    -   id: check-yaml
    -   id: no-commit-to-branch

-   repo: https://github.com/hukkin/mdformat
    rev: 0.7.22
    hooks:
    -   id: mdformat
        additional_dependencies:
        - mdformat-gfm

-   repo: https://github.com/golangci/golangci-lint
    rev: v2.1.2
    hooks:
    -   id: golangci-lint-fmt
